### ISSUE TITLE
Error when creating Connector 

### ISSUE THREAD

**Issue by cschriewer** [mediaopt/paypal-commercetools-connector#52]
When I try to create a Connector in the Merchant Center by selecting "Request Preview" or "Publish for private use", I get the error
"The file connect.yaml at git@github.com:mediaopt/paypal-commercetools-connector.git with the tag 1.0.2 is not valid"

This is possibly due to this change:
https://docs.commercetools.com/connect/releases/2024-01-30-changed-the-applicationtype-for-custom-applications
> The applicationType for [Custom Applications](https://docs.commercetools.com/custom-applications) in [connect.yaml](https://docs.commercetools.com/connect/development#configure-connectyaml) has changed from mc-app to merchant-center-custom-application.

**Comment by LiudmylaMasliuk** [comment]
Thank you for reporting this error. We are already working on it and a new version will be released as soon as it goes through the certification process at commercetools.

**Comment by LiudmylaMasliuk** [comment]
@cschriewer  , could you please tell us in which shop do you want to install our PayPal connector or for which company do you work? 
Thank you
